# Generated by Django 5.1.15 on 2026-08-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_remove_sitesettings_logo_url_sitesettings_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="vendor_upi_id",
            field=models.CharField(
                blank=True,
                help_text="UPI ID (e.g. yourname@okbank) used to generate the checkout payment QR code.",
                max_length=120,
                verbose_name="Vendor UPI ID",
            ),
        ),
    ]
