# Generated by Django 5.1.15 on 2026-08-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0009_alter_heroslide_title_help"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepagesection",
            name="section_type",
            field=models.CharField(
                choices=[
                    ("hero_slider", "Hero Slider"),
                    ("shop_by_category", "Shop by Category"),
                    ("featured_products", "Featured Products"),
                    ("new_arrivals", "New Arrivals"),
                    ("rental", "Rental"),
                    ("best_sellers", "Best Sellers"),
                    ("featured_brands", "Featured Brands"),
                    ("subscription_banner", "Subscription Banner"),
                    ("marketing_features", "Marketing Feature Cards"),
                    ("reviews", "Reviews"),
                    ("instagram_gallery", "Instagram Gallery"),
                    ("newsletter", "Newsletter"),
                ],
                db_index=True,
                max_length=40,
                verbose_name="Section type",
            ),
        ),
    ]
