# Generated by Django 5.1.15 on 2026-07-07 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_phase9_admin_cms_marketing_reports"),
        ("catalog", "0002_phase10_performance_seo"),
        ("corporate", "0001_phase8_corporate_portal"),
        ("orders", "0004_phase9_admin_cms_marketing_reports"),
        ("recurring", "0002_phase9_admin_cms_marketing_reports"),
    ]

    operations = [
        migrations.AlterField(
            model_name="corporateinvoice",
            name="corporate_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="corporate.corporateorder",
                verbose_name="Corporate order",
            ),
        ),
        migrations.AlterField(
            model_name="corporateinvoice",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Timestamp when this record was first created.",
                verbose_name="Created at",
            ),
        ),
        migrations.AlterField(
            model_name="corporateinvoice",
            name="generated_at",
            field=models.DateTimeField(verbose_name="Generated at"),
        ),
        migrations.AlterField(
            model_name="corporateinvoice",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="corporateinvoice",
            name="pdf_url",
            field=models.URLField(verbose_name="PDF URL"),
        ),
        migrations.AlterField(
            model_name="corporateinvoice",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="Timestamp when this record was last modified.",
                verbose_name="Updated at",
            ),
        ),
        migrations.AlterField(
            model_name="corporateorder",
            name="corporate_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="corporate_orders",
                to="accounts.corporateaccount",
                verbose_name="Corporate account",
            ),
        ),
        migrations.AlterField(
            model_name="corporateorder",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Timestamp when this record was first created.",
                verbose_name="Created at",
            ),
        ),
        migrations.AlterField(
            model_name="corporateorder",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="corporateorder",
            name="is_recurring",
            field=models.BooleanField(default=False, verbose_name="Is recurring"),
        ),
        migrations.AlterField(
            model_name="corporateorder",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="corporateorder",
            name="quote_status",
            field=models.CharField(
                choices=[
                    ("requested", "Requested"),
                    ("quoted", "Quoted"),
                    ("approved", "Approved"),
                    ("ordered", "Ordered"),
                ],
                db_index=True,
                default="requested",
                max_length=20,
                verbose_name="Quote status",
            ),
        ),
        migrations.AlterField(
            model_name="corporateorder",
            name="recurring_schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="corporate_orders",
                to="recurring.recurringschedule",
                verbose_name="Recurring schedule",
            ),
        ),
        migrations.AlterField(
            model_name="corporateorder",
            name="retail_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="corporate_orders",
                to="orders.order",
                verbose_name="Converted retail order",
            ),
        ),
        migrations.AlterField(
            model_name="corporateorder",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="Timestamp when this record was last modified.",
                verbose_name="Updated at",
            ),
        ),
        migrations.AlterField(
            model_name="corporateorderitem",
            name="corporate_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="corporate.corporateorder",
                verbose_name="Corporate order",
            ),
        ),
        migrations.AlterField(
            model_name="corporateorderitem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Timestamp when this record was first created.",
                verbose_name="Created at",
            ),
        ),
        migrations.AlterField(
            model_name="corporateorderitem",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="corporateorderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="corporate_order_items",
                to="catalog.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="corporateorderitem",
            name="quantity",
            field=models.PositiveIntegerField(verbose_name="Quantity"),
        ),
        migrations.AlterField(
            model_name="corporateorderitem",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Unit price"),
        ),
        migrations.AlterField(
            model_name="corporateorderitem",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="Timestamp when this record was last modified.",
                verbose_name="Updated at",
            ),
        ),
        migrations.AlterField(
            model_name="corporateorderitem",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="corporate_order_items",
                to="catalog.productvariant",
                verbose_name="Variant",
            ),
        ),
    ]
