# Generated by Django 5.1.15 on 2026-08-04 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_phase10_performance_seo"),
        ("checkout", "0002_remove_checkoutsession_delivery_slot"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkoutsession",
            name="buy_now_item",
            field=models.ForeignKey(
                blank=True,
                help_text="When set, checkout is scoped to this single cart line instead of the whole cart.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="buy_now_checkout_sessions",
                to="cart.cartitem",
                verbose_name="Buy Now item",
            ),
        ),
    ]
