# Generated by Django 5.1.15 on 2026-07-07 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_phase3_product_catalog"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("delivery", "0002_phase5_gift_customization"),
    ]

    operations = [
        migrations.CreateModel(
            name="GiftLineItemRef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gift line item reference",
                "verbose_name_plural": "Gift line item references",
            },
        ),
        migrations.CreateModel(
            name="GiftPhotoUploadOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "price_delta",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Amount added to the line item when this option is selected.",
                        max_digits=12,
                        verbose_name="Price delta",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="When False, option is hidden from the gift builder.",
                        verbose_name="Is active",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Photo upload option",
                "verbose_name_plural": "Photo upload options",
            },
        ),
        migrations.CreateModel(
            name="GiftWrapOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "price_delta",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Amount added to the line item when this option is selected.",
                        max_digits=12,
                        verbose_name="Price delta",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="When False, option is hidden from the gift builder.",
                        verbose_name="Is active",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("premium", "Premium"),
                            ("luxury_box", "Luxury Box"),
                            ("transparent", "Transparent"),
                            ("eco_friendly", "Eco Friendly"),
                        ],
                        max_length=30,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gift wrap option",
                "verbose_name_plural": "Gift wrap options",
            },
        ),
        migrations.CreateModel(
            name="RibbonOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "price_delta",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Amount added to the line item when this option is selected.",
                        max_digits=12,
                        verbose_name="Price delta",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="When False, option is hidden from the gift builder.",
                        verbose_name="Is active",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("red", "Red"),
                            ("gold", "Gold"),
                            ("white", "White"),
                            ("black", "Black"),
                            ("pink", "Pink"),
                            ("blue", "Blue"),
                            ("theme", "Theme"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ribbon option",
                "verbose_name_plural": "Ribbon options",
            },
        ),
        migrations.CreateModel(
            name="GreetingCardDesign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Name")),
                (
                    "image",
                    models.ImageField(
                        help_text="Preview image shown in the greeting card gallery.",
                        upload_to="gifting/greeting_cards/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True, verbose_name="Is active"),
                ),
                (
                    "occasion",
                    models.ForeignKey(
                        help_text="Occasion this design is associated with.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="greeting_card_designs",
                        to="catalog.occasion",
                        verbose_name="Occasion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Greeting card design",
                "verbose_name_plural": "Greeting card designs",
            },
        ),
        migrations.CreateModel(
            name="GiftCustomizationSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "line_item_object_id",
                    models.PositiveBigIntegerField(verbose_name="Line item object ID"),
                ),
                (
                    "personal_message",
                    models.TextField(blank=True, max_length=250, verbose_name="Personal message"),
                ),
                (
                    "delivery_date",
                    models.DateField(
                        blank=True, db_index=True, null=True, verbose_name="Delivery date"
                    ),
                ),
                (
                    "delivery_instructions",
                    models.TextField(blank=True, verbose_name="Delivery instructions"),
                ),
                (
                    "recipient_phone",
                    models.CharField(blank=True, max_length=30, verbose_name="Recipient phone"),
                ),
                (
                    "is_anonymous",
                    models.BooleanField(default=False, verbose_name="Anonymous delivery"),
                ),
                (
                    "reveal_sender_after_delivery",
                    models.BooleanField(default=False, verbose_name="Reveal sender after delivery"),
                ),
                (
                    "is_gift_receipt",
                    models.BooleanField(
                        default=False,
                        help_text="When True, pricing is excluded from the packing slip.",
                        verbose_name="Gift receipt",
                    ),
                ),
                (
                    "snapshot_json",
                    models.JSONField(
                        default=dict,
                        help_text="Full resolved selection and prices at snapshot creation time.",
                        verbose_name="Snapshot JSON",
                    ),
                ),
                (
                    "delivery_slot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gift_snapshots",
                        to="delivery.deliveryslot",
                        verbose_name="Delivery slot",
                    ),
                ),
                (
                    "line_item_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gift_snapshots",
                        to="contenttypes.contenttype",
                        verbose_name="Line item content type",
                    ),
                ),
                (
                    "photo_upload",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="snapshots",
                        to="gifting.giftphotouploadoption",
                        verbose_name="Photo upload",
                    ),
                ),
                (
                    "gift_wrap",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="snapshots",
                        to="gifting.giftwrapoption",
                        verbose_name="Gift wrap",
                    ),
                ),
                (
                    "greeting_card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="snapshots",
                        to="gifting.greetingcarddesign",
                        verbose_name="Greeting card",
                    ),
                ),
                (
                    "ribbon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="snapshots",
                        to="gifting.ribbonoption",
                        verbose_name="Ribbon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gift customization snapshot",
                "verbose_name_plural": "Gift customization snapshots",
            },
        ),
        migrations.CreateModel(
            name="GiftAddonEligibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                ("object_id", models.PositiveBigIntegerField(verbose_name="Object ID")),
                (
                    "addon_product",
                    models.ForeignKey(
                        help_text="Catalog product offered as an add-on for the primary target.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gift_addon_eligibilities",
                        to="catalog.product",
                        verbose_name="Add-on product",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gift_addon_eligibilities",
                        to="contenttypes.contenttype",
                        verbose_name="Content type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gift add-on eligibility",
                "verbose_name_plural": "Gift add-on eligibilities",
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"], name="gifting_addon_elig_ct_obj_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("content_type", "object_id", "addon_product"),
                        name="gifting_addon_eligibility_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="GiftCustomizationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveBigIntegerField(
                        help_text="Primary key of the customizable product instance.",
                        verbose_name="Object ID",
                    ),
                ),
                (
                    "allows_personal_message",
                    models.BooleanField(default=True, verbose_name="Personal message"),
                ),
                (
                    "allows_greeting_card",
                    models.BooleanField(default=True, verbose_name="Greeting card"),
                ),
                ("allows_gift_wrap", models.BooleanField(default=True, verbose_name="Gift wrap")),
                ("allows_ribbon", models.BooleanField(default=True, verbose_name="Ribbon")),
                ("allows_addons", models.BooleanField(default=True, verbose_name="Add-ons")),
                (
                    "allows_anonymous",
                    models.BooleanField(default=True, verbose_name="Anonymous delivery"),
                ),
                (
                    "allows_gift_receipt",
                    models.BooleanField(default=True, verbose_name="Gift receipt"),
                ),
                (
                    "allows_midnight_delivery",
                    models.BooleanField(default=False, verbose_name="Midnight delivery"),
                ),
                (
                    "allows_photo_upload",
                    models.BooleanField(
                        default=False,
                        help_text="When True, customer may attach a photo upload option at checkout.",
                        verbose_name="Photo upload",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="Django content type of the customizable product instance.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gift_customization_configs",
                        to="contenttypes.contenttype",
                        verbose_name="Content type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gift customization config",
                "verbose_name_plural": "Gift customization configs",
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"], name="gifting_config_ct_obj_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("content_type", "object_id"), name="gifting_config_unique_target"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="GiftSnapshotAddon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "price_at_time_of_purchase",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Resolved catalog price when the snapshot was created.",
                        max_digits=12,
                        verbose_name="Price at purchase",
                    ),
                ),
                (
                    "addon_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gift_snapshot_addons",
                        to="catalog.product",
                        verbose_name="Add-on product",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshot_addons",
                        to="gifting.giftcustomizationsnapshot",
                        verbose_name="Snapshot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gift snapshot add-on",
                "verbose_name_plural": "Gift snapshot add-ons",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("snapshot", "addon_product"), name="gifting_snapshot_addon_unique"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="greetingcarddesign",
            index=models.Index(
                fields=["is_active", "occasion_id"], name="gifting_card_active_occ_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="giftcustomizationsnapshot",
            index=models.Index(
                fields=["line_item_content_type", "line_item_object_id"],
                name="gifting_snapshot_line_item_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="giftcustomizationsnapshot",
            index=models.Index(fields=["delivery_date"], name="gifting_snapshot_del_date_idx"),
        ),
    ]
