# Generated by Django 5.1.15 on 2026-07-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifting', '0001_phase5_gift_customization'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcustomizationsnapshot',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Set True the moment this snapshot becomes part of a placed order. Once locked, it can never be rebuilt or overwritten again.', verbose_name='Locked'),
        ),
    ]
