# Generated by Django 5.1.15 on 2026-08-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_alter_productvariant_variant_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productwholesaletier",
            name="max_quantity",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Max Quantity"),
        ),
    ]
