# Generated by Django 5.1.15 on 2026-07-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_phase10_performance_seo'),
        ('catalog', '0003_recipient_product_recipients'),
        ('gifting', '0002_giftcustomizationsnapshot_is_locked'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='cart_item_unique_product_variant',
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('gift_customization_snapshot__isnull', True)), fields=('cart', 'product', 'variant'), name='cart_item_unique_product_variant_no_gift'),
        ),
    ]
